### ISSUE TITLE
Gem not found in GitHub

### ISSUE THREAD

**Issue by mikelarkin** [tobi/clarity#1]
Could only install it from http://gemcutter.org

Might want to update the docs or else turn it into a gem with GitHub...

**Comment by jstorimer** [comment]
@mikelarkin check out http://github.com/blog/515-gem-building-is-defunct

**Comment by mikelarkin** [comment]
Ah, thanks! That explains it then.

**Comment by tobi** [comment]
Yea github gems are gone and gemcutter will be gems.rubygems.com very soon.
