### ISSUE TITLE
Unknown command clarity

### ISSUE THREAD

**Issue by asvist** [tobi/clarity#16]
<pre>user@ubuntu:~$ sudo gem install clarity
PostInstall.txt
Successfully installed clarity-0.9.8
1 gem installed
Installing ri documentation for clarity-0.9.8...
Installing RDoc documentation for clarity-0.9.8...
Could not find main page README.rdoc
Could not find main page README.rdoc
Could not find main page README.rdoc
Could not find main page README.rdoc
user@ubuntu:~$ clarity --username=admin --password=secret --port=8989 /var/log
clarity: command not found
user@ubuntu:~$ </pre>

Can you please help to resolve this?
Thank yiou.

**Comment by pnewb** [comment]
If it's not in your path, you might have to track down the install location.  On my 10.04 ubuntu box it was found here: /var/lib/gems/1.8/bin/clarity

**Comment by asvist** [comment]
Thanks for the answer, but I already tried it befor. The same result:

<pre>
user@ubuntu:~$ cd /var/lib/gems/1.8/bin
user@ubuntu:/var/lib/gems/1.8/bin$ ls
clarity
user@ubuntu:/var/lib/gems/1.8/bin$ clarity --username=admin --password=secret --port=8989 /var/log
clarity: command not found
</pre>

**Comment by pnewb** [comment]
You got 1/2 way between two possible answers.

With linux you can call a program that exists in your path (if you want to see what's in that do: echo $PATH): clarity --username=admin
If that program's not in your path you can call one with a full path: /var/lib/gems/1.8/bin/clarity --username=admin
OR, you can change into the directory where that program exists, and then tell the system that the program you're calling exists in the directory you're currently in:
cd /var/lib/gems/1.8/bin/
./clarity --username=admin

it's that dot slash at the front that's important.

**Comment by asvist** [comment]
Thanks a lot! It works fine now!
