### ISSUE TITLE
can't convert String into Array (TypeError)

### ISSUE THREAD

**Issue by ghost** [tobi/clarity#20]
after installing clarity i was trying run it 
by 
# clarity --username=admin --password=secret  --port=8989  --include="httpd/_.log_" /var/log

i got following error

/usr/lib/ruby/gems/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:47:in `+': can't convert String into Array (TypeError)
    from /usr/lib/ruby/gems/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:47:in`execute'
    from /usr/lib/ruby/1.8/optparse.rb:1267:in `call'
    from /usr/lib/ruby/1.8/optparse.rb:1267:in`parse_in_order'
    from /usr/lib/ruby/1.8/optparse.rb:1254:in `catch'
    from /usr/lib/ruby/1.8/optparse.rb:1254:in`parse_in_order'
    from /usr/lib/ruby/1.8/optparse.rb:1248:in `order!'
    from /usr/lib/ruby/1.8/optparse.rb:1339:in`permute!'
    from /usr/lib/ruby/1.8/optparse.rb:1360:in `parse!'
    from /usr/lib/ruby/gems/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:76:in`execute'
    from /usr/lib/ruby/1.8/optparse.rb:1724:in `options'
    from /usr/lib/ruby/gems/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb:20:in`execute'
    from /usr/lib/ruby/gems/1.8/gems/clarity-0.9.8/bin/clarity:10
    from /usr/bin/clarity:19:in `load'
    from /usr/bin/clarity:19

**Comment by Antronin** [comment]
I think you have an outdated version of clarity.
I had the same issue and if you want to manually correct it, change in /usr/lib/ruby/gems/1.8/gems/clarity-0.9.8/lib/clarity/cli.rb at line 47 the '+=' signs to '<<'.
Or simply upgrade as I think it is already corrected.

**Comment by ghost** [comment]
Thanks a lot Antronin
