### ISSUE TITLE
no such file to load -- action_view (LoadError)

### ISSUE THREAD

**Issue by jmgarnier** [tobi/clarity#3]
It sounds like clarity has another dependency: Rails

Could you please document the version of Rails you are using?

Thank you

**Comment by tobi** [comment]
I'm kinda surprised by that. We definitely don't use rails. I'll investigate.

**Comment by jmgarnier** [comment]
Line 1 in http://github.com/tobi/clarity/blob/master/lib/clarity/renderers/log_renderer.rb

**Comment by tobi** [comment]
should be gone now.
