### ISSUE TITLE
Filenames that don't end in .log are explicitly not supported

### ISSUE THREAD

**Issue by ckdake** [tobi/clarity#4]
There are a few things hardcoded in that seem to prevent log files with extensions other than .log.  I changed line 7 of /usr/lib/ruby/gems/1.8/gems/clarity-0.9.2/lib/clarity/commands/tail_command_builder.rb and set the default value of log_files in /usr/lib/ruby/gems/1.8/gems/clarity-0.9.2/lib/clarity/cli.rb to "['**/**']" which makes things work here for our web logs where are formatted like access_log.1  .  These changes probably make sense for a lot of situations, and in cases where .log does matter, it could be specified in the command line when starting clarity. Thanks!

**Comment by tobi** [comment]
ok by default we will now look for **/_log_ but if you add --include MASK switches we clear this one out, this means you can use clarity /var/log --include '**/*' to include all files .
